language: node_js
sudo: false
node_js:
  - 8
addons:
  apt:
    packages:
      - xvfb
install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1366x768x24 > /dev/null 2>&1 &
  - npm i
script:
  - npm run docs:build
  - cd ./docs
  - git init
  - git add --all .
  - git commit -m "Travis CI Auto Builder"
  - git push --quiet --force https://$REPO_TOKEN@github.com/macacajs/macaca-reporter.git master:gh-pages
  - cd ..
  - npm run lint
  - npm run serve && npm run test
after_script:
  - npm install coveralls@2 && cat ./coverage/lcov.info | coveralls
